// Background service worker
chrome.runtime.onInstalled.addListener(() => {
  chrome.storage.local.get(['readmarks'], function (result) {
    if (!result.readmarks) {
      chrome.storage.local.set({ readmarks: [] });
    }
  });
});

// ── Gemini API tagging ──────────────────────────────────────────────────────
// All external fetch calls live here. Extension pages and content scripts relay
// via chrome.runtime.sendMessage({ type: 'GENERATE_TAGS', text: '...' }).
// API key is loaded from config.js (gitignored, generated by generate-config.js).

try {
    importScripts('config.js');
} catch (e) {
    console.warn('[Jot/bg] config.js missing — run: node generate-config.js');
}
var GEMINI_ENDPOINT = 'https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-lite:generateContent';
var GEMINI_TIMEOUT_MS = 15000;

var GEMINI_PROMPT =
    'You are a tagging assistant for a personal notes and highlights tool. ' +
    'Given the following note text, return a JSON object with exactly two fields:\n' +
    '- \'category\': one value from this fixed list only:\n' +
    '  [research, idea, quote, task, reference, inspiration, question, reflection]\n' +
    '- \'tags\': an array of 2–4 short freeform descriptive tags that capture the specific ' +
    'topic, theme, or subject of the note (e.g. \'typography\', \'color theory\', \'machine learning\')\n\n' +
    'Respond with raw JSON only. No markdown, no backticks, no explanation. Note text: ';

function stripFences(str) {
    return str.replace(/^```(?:json)?\n?/m, '').replace(/```\s*$/m, '').trim();
}

chrome.runtime.onMessage.addListener(function (message, sender, sendResponse) {
    if (!message || message.type !== 'GENERATE_TAGS') return false;

    if (!message.text || !GEMINI_API_KEY) {
        sendResponse(null);
        return false;
    }

    var controller = new AbortController();
    var timeoutId = setTimeout(function () { controller.abort(); }, GEMINI_TIMEOUT_MS);

    fetch(GEMINI_ENDPOINT + '?key=' + GEMINI_API_KEY, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
            contents: [{ parts: [{ text: GEMINI_PROMPT + message.text }] }]
        }),
        signal: controller.signal
    })
    .then(function (response) {
        clearTimeout(timeoutId);
        if (!response.ok) {
            return response.text().then(function (b) {
                console.log('[Jot/bg] status:', response.status, JSON.parse(b).error.message.split('\n')[0]);
                return null;
            });
        }
        return response.json();
    })
    .then(function (data) {
        if (!data) { sendResponse(null); return; }
        var raw = data.candidates &&
                  data.candidates[0] &&
                  data.candidates[0].content &&
                  data.candidates[0].content.parts &&
                  data.candidates[0].content.parts[0] &&
                  data.candidates[0].content.parts[0].text;
        if (!raw) { sendResponse(null); return; }
        try {
            var parsed = JSON.parse(stripFences(raw));
            if (!parsed.category || !Array.isArray(parsed.tags)) {
                sendResponse(null);
                return;
            }
            sendResponse({
                category: String(parsed.category),
                tags: parsed.tags.map(String)
            });
        } catch (e) {
            sendResponse(null);
        }
    })
    .catch(function () {
        clearTimeout(timeoutId);
        sendResponse(null);
    });

    return true; // keep message channel open for async sendResponse
});
